id: A853DAB25
title: 'The Great Treasure of a Hundred Blessings: A Prayer for the Long Life of Ḍākinī
  Muntso Rinpoche'
type: translation
pechas:
- I3958E515
- IB9D98F79
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:39:53.349113
  last_modified_at: 2023-01-04 12:39:53.349137
  collections:
  - Jetsünma Muntso Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  I3958E515/4E21: 15DF
  IB9D98F79/9C92: 15DF
